name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkg:
          - "."
          - "orchestrator"
          - "sandbox"
          - "kiosk-api"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm install
        working-directory: ${{ matrix.pkg }}

      - name: Typecheck
        run: npm run typecheck --if-present
        working-directory: ${{ matrix.pkg }}

      - name: Lint
        run: npm run lint --if-present
        working-directory: ${{ matrix.pkg }}

      - name: Build
        run: npm run build --if-present
        working-directory: ${{ matrix.pkg }}
