name: CI

on:
  push:
    branches: [ main ]
    paths:
      - "sandbox/**"
      - "orchestrator/**"
      - ".github/workflows/**"
      - "data/**"
  pull_request:
    branches: [ main ]

jobs:
  sanity:
    name: Sanity Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List changed files
        run: git diff --name-only ${{ github.sha }}~1 ${{ github.sha }} || true
      - name: Validate JSON (quick check)
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          find . -name "*.json" -not -path "./node_modules/*" -print0 | xargs -0 -I{} sh -c 'jq . {} >/dev/null' || true

  sandbox-normalize:
    name: Sandbox → inventory.json
    needs: sanity
    if: ${{ hashFiles('sandbox/package.json') != '' && (github.event_name == 'pull_request' || github.event_name == 'push') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sandbox
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run normalize
      - name: Upload inventory.json artifact
        uses: actions/upload-artifact@v4
        with:
          name: inventory.json
          path: sandbox/inventory.json

  orchestrator-build:
    name: Orchestrator Build
    needs: sanity
    if: ${{ hashFiles('orchestrator/package.json') != '' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: orchestrator
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run -s dev -- --help || true  # smoke check; replace with real build/test later
